version: '3.4'

services:
  microstack.api:
    image: ${DOCKER_REGISTRY-}microstackapi
    build:
      context: .
      dockerfile: MicroStack.Api/Dockerfile

  microstack.client:
    image: ${DOCKER_REGISTRY-}microstackclient
    build:
      context: .
      dockerfile: MicroStack.Client/Dockerfile

  microstack.db:
    image: mongo

